export interface Question {
  id: number;
  text: string;
  options: string[];
  correctAnswer: string; // 'A', 'B', 'C', or 'D'
}

export const questions: Question[] = [
  // Part 1
  { id: 1, text: "Who will ________ the children while you are away on business?", options: ["look after", "look for", "look at", "look up"], correctAnswer: "A" },
  { id: 2, text: "Remember to ________ your shoes when you go inside the temple.", options: ["take up", "take in", "take off", "take on"], correctAnswer: "C" },
  { id: 3, text: "It took my grandfather a long time to ________ the severe illness.", options: ["get over", "get up", "get out", "get in"], correctAnswer: "A" },
  { id: 4, text: "The football match had to be ________ because of the heavy rain.", options: ["put out", "put off", "put on", "put up"], correctAnswer: "B" },
  { id: 5, text: "It’s too loud. Can you ________ the volume of the radio, please?", options: ["turn on", "turn up", "turn down", "turn off"], correctAnswer: "C" },
  { id: 6, text: "She was reading a book when the lights ________.", options: ["went down", "went out", "went up", "went off"], correctAnswer: "B" },
  { id: 7, text: "I ________ an old photo of my grandmother while I was cleaning the attic.", options: ["came across", "came up with", "came back", "came from"], correctAnswer: "A" },
  { id: 8, text: "My doctor advised me to ________ drinking too much coffee.", options: ["give back", "give up", "give away", "give in"], correctAnswer: "B" },
  { id: 9, text: "We are looking forward to ________ from you soon.", options: ["hear", "heard", "hearing", "be heard"], correctAnswer: "C" },
  { id: 10, text: "My brother decided to ________ swimming to stay healthy.", options: ["take up", "take after", "take over", "take away"], correctAnswer: "A" },
  { id: 11, text: "Do you ________ well with your new classmates?", options: ["get over", "get on", "get up", "get by"], correctAnswer: "B" },
  { id: 12, text: "I can’t ________ his bad behavior anymore. It's driving me crazy!", options: ["put up with", "put down", "put away", "put forward"], correctAnswer: "A" },
  { id: 13, text: "We waited for Mary for an hour, but she didn’t ________.", options: ["turn out", "turn down", "turn up", "turn into"], correctAnswer: "C" },
  { id: 14, text: "My alarm clock didn't ________ this morning, so I was late for school.", options: ["go out", "go off", "go on", "go away"], correctAnswer: "B" },
  { id: 15, text: "The team ________ a brilliant idea for the environmental project.", options: ["came up", "came into", "came up with", "came out"], correctAnswer: "C" },
  { id: 16, text: "The two sisters had a big argument, but they ________ yesterday.", options: ["made up", "made out", "made for", "made of"], correctAnswer: "A" },
  { id: 17, text: "After her parents passed away, she was ________ by her aunt.", options: ["brought out", "brought up", "brought down", "brought about"], correctAnswer: "B" },
  { id: 18, text: "Our car ________ on the way to the airport, so we almost missed the flight.", options: ["broke out", "broke into", "broke down", "broke up"], correctAnswer: "C" },
  { id: 19, text: "The school festival was ________ due to the storm.", options: ["called off", "called for", "called back", "called up"], correctAnswer: "A" },
  { id: 20, text: "Let's go to the supermarket. We have ________ milk and eggs.", options: ["run into", "run out of", "run away from", "run out"], correctAnswer: "B" },
  { id: 21, text: "After graduating, he plans to ________ his own software company.", options: ["set off", "set out", "set up", "set in"], correctAnswer: "C" },
  { id: 22, text: "If you don't know the meaning of this new word, ________ in the dictionary.", options: ["look it up", "look after it", "look it for", "look it into"], correctAnswer: "A" },
  { id: 23, text: "She ________ her mother; they both have curly hair and blue eyes.", options: ["takes care of", "takes after", "takes over", "takes off"], correctAnswer: "B" },
  { id: 24, text: "Go ahead! I will ________ you in a few minutes.", options: ["catch up with", "catch on", "catch out", "catch up"], correctAnswer: "A" },
  { id: 25, text: "Tom ________ university after his first year to start a business.", options: ["dropped by", "dropped in", "dropped out of", "dropped off"], correctAnswer: "C" },

  // Part 2
  { id: 26, text: "The police are trying to ________ the cause of the accident.", options: ["look into", "look up", "look for", "look after"], correctAnswer: "A" },
  { id: 27, text: "The freezing temperatures ________ the water ________ ice.", options: ["turned / off", "turned / into", "turned / down", "turned / up"], correctAnswer: "B" },
  { id: 28, text: "Don't ________ my secret to anyone, please!", options: ["give up", "give back", "give away", "give in"], correctAnswer: "C" },
  { id: 29, text: "Despite the loud noise outside, he ________ studying for his exam.", options: ["went on", "went off", "went out", "went down"], correctAnswer: "A" },
  { id: 30, text: "It's freezing outside. You should ________ your warm coat.", options: ["put off", "put on", "put out", "put away"], correctAnswer: "B" },
  { id: 31, text: "The teacher asked us to ________ the important notes from the blackboard.", options: ["take off", "take down", "take up", "take over"], correctAnswer: "B" },
  { id: 32, text: "I tried to call her all morning, but I couldn't ________.", options: ["get through", "get over", "get by", "get in"], correctAnswer: "A" },
  { id: 33, text: "The surprise party ________ perfectly, and everyone was so happy.", options: ["came about", "came off", "came out", "came down with"], correctAnswer: "B" },
  { id: 34, text: "The new policies will ________ major changes in the education system.", options: ["bring up", "bring down", "bring about", "bring out"], correctAnswer: "C" },
  { id: 35, text: "The local news reported that thieves ________ the jewelry store last night.", options: ["broke down", "broke out", "broke into", "broke up"], correctAnswer: "C" },
  { id: 36, text: "This difficult situation ________ immediate action from the government.", options: ["calls off", "calls for", "calls back", "calls on"], correctAnswer: "B" },
  { id: 37, text: "The scientists are ________ an important experiment in the lab.", options: ["carrying on", "carrying out", "carrying away", "carrying over"], correctAnswer: "B" },
  { id: 38, text: "We hope the dark clouds will ________ for our picnic tomorrow.", options: ["clear up", "clear out", "clear away", "clear off"], correctAnswer: "A" },
  { id: 39, text: "You can always ________ me if you need help with your homework.", options: ["count on", "hold on", "keep on", "put on"], correctAnswer: "A" },
  { id: 40, text: "Without protection, many wild animals are in danger of ________.", options: ["passing away", "breaking out", "dying out", "leaving out"], correctAnswer: "C" },
  { id: 41, text: "Please ________ this application form with your personal details and sign it.", options: ["hand in", "fill in", "show off", "try on"], correctAnswer: "B" },
  { id: 42, text: "All students must ________ their final essays by Friday.", options: ["hand in", "find out", "point out", "stand out"], correctAnswer: "A" },
  { id: 43, text: "He walks so fast that I can hardly ________ him.", options: ["catch up", "keep up with", "go along with", "put up with"], correctAnswer: "B" },
  { id: 44, text: "It was so hot and stuffy in the room that she almost ________.", options: ["passed away", "passed out", "passed by", "passed down"], correctAnswer: "B" },
  { id: 45, text: "Guess who I ________ at the supermarket today! My old English teacher.", options: ["ran out of", "ran into", "ran after", "ran away"], correctAnswer: "B" },
  { id: 46, text: "He bought an expensive new sports car just to ________.", options: ["show up", "show off", "set off", "turn up"], correctAnswer: "B" },
  { id: 47, text: "What does the abbreviation 'WHO' ________?", options: ["stand by", "stand for", "stand out", "stand up"], correctAnswer: "B" },
  { id: 48, text: "I need some time to ________ your offer before making a final decision.", options: ["think over", "think of", "think about", "think out"], correctAnswer: "A" },
  { id: 49, text: "Can I ________ this dress to see if it fits me?", options: ["put on", "try on", "turn on", "get on"], correctAnswer: "B" },
  { id: 50, text: "After dinner, it's my turn to ________.", options: ["wipe out", "wash up", "clear up", "clean out"], correctAnswer: "B" },

  // Part 3
  { id: 51, text: "\"______! There's a car coming towards us!\"", options: ["Look out", "Look up", "Look into", "Look through"], correctAnswer: "A" },
  { id: 52, text: "Many teenagers ______ pop stars as their role models.", options: ["look down on", "look up to", "get along with", "catch up with"], correctAnswer: "B" },
  { id: 53, text: "When the old manager retired, Mr. Smith ______ the company.", options: ["took on", "took off", "took over", "took up"], correctAnswer: "C" },
  { id: 54, text: "It's hard to ______ on my small salary, but I manage somehow.", options: ["get by", "get over", "get off", "get down"], correctAnswer: "A" },
  { id: 55, text: "We need to ______ the bus at the next stop to reach the museum.", options: ["get in", "get off", "get on", "get out"], correctAnswer: "B" },
  { id: 56, text: "She ______ some money every month for her summer holiday.", options: ["puts off", "puts out", "puts aside", "puts up"], correctAnswer: "C" },
  { id: 57, text: "It took the brave firefighters two hours to ________ the fire.", options: ["put off", "put out", "put up", "put away"], correctAnswer: "B" },
  { id: 58, text: "Please remember to ______ the lights before you leave the room.", options: ["turn on", "turn off", "turn up", "turn down"], correctAnswer: "B" },
  { id: 59, text: "Let's ______ the grammar rules once more before taking the test.", options: ["go over", "go off", "go away", "go out"], correctAnswer: "A" },
  { id: 60, text: "I think I'm ______ the flu; I have a headache and a sore throat.", options: ["coming down with", "coming up with", "coming out", "coming across"], correctAnswer: "A" },
  { id: 61, text: "The handwriting is so bad that I can't ______ what it says.", options: ["make up", "make out", "make for", "make over"], correctAnswer: "B" },
  { id: 62, text: "He bought her a nice present to ______ forgetting her birthday.", options: ["make up for", "look forward to", "keep up with", "catch up with"], correctAnswer: "A" },
  { id: 63, text: "These beautiful flowers ______ a very sweet smell.", options: ["give up", "give away", "give in", "give off"], correctAnswer: "D" },
  { id: 64, text: "World War II ______ in 1939 and ended in 1945.", options: ["broke down", "broke out", "broke into", "broke up"], correctAnswer: "B" },
  { id: 65, text: "Don't stop! Just ______ working until you finish the task.", options: ["carry out", "carry on", "catch on", "call off"], correctAnswer: "B" },
  { id: 66, text: "The doctor advised him to ______ eating fast food to lose weight.", options: ["cut down on", "come down with", "keep up with", "put up with"], correctAnswer: "A" },
  { id: 67, text: "You can't always ______ your parents; you must learn to be independent.", options: ["rely on", "count in", "live on", "hold on"], correctAnswer: "A" },
  { id: 68, text: "I will ______ your house this afternoon to give you the notebook.", options: ["drop out", "drop by", "drop off", "drop down"], correctAnswer: "B" },
  { id: 69, text: "If you don't study hard, you will ______ your classmates.", options: ["fall behind", "drop out", "pass away", "leave out"], correctAnswer: "A" },
  { id: 70, text: "We need to ______ where the meeting will take place.", options: ["hand in", "find out", "point out", "stand out"], correctAnswer: "B" },
  { id: 71, text: "When I ______, I want to be a doctor to help sick people.", options: ["grow up", "stand up", "wake up", "get up"], correctAnswer: "A" },
  { id: 72, text: "\"Can I speak to Peter, please?\" - \"______, I'll get him for you.\"", options: ["Keep on", "Go on", "Hold on", "Carry on"], correctAnswer: "C" },
  { id: 73, text: "You can ______ this question if you don't know the answer and do it later.", options: ["cross out", "wipe out", "leave out", "point out"], correctAnswer: "C" },
  { id: 74, text: "I promise I will ______ the money I borrowed from you next week.", options: ["pay back", "give back", "take back", "call back"], correctAnswer: "A" },
  { id: 75, text: "We have to ______ early tomorrow morning to avoid the heavy traffic.", options: ["set up", "set off", "set in", "set down"], correctAnswer: "B" },

  // Part 4
  { id: 76, text: "As people get older, they often ______ their childhood with fond memories.", options: ["look back on", "look down on", "look forward to", "look out for"], correctAnswer: "A" },
  { id: 77, text: "You shouldn't ______ people just because they are poor.", options: ["look up to", "look down on", "get on with", "keep up with"], correctAnswer: "B" },
  { id: 78, text: "The teacher spoke so fast that I couldn't ______ what she was saying.", options: ["take away", "take in", "take back", "take up"], correctAnswer: "B" },
  { id: 79, text: "That shirt has a hole in it. You should ______ it ______ to the shop.", options: ["take / away", "take / down", "take / back", "take / off"], correctAnswer: "C" },
  { id: 80, text: "The bank robbers managed to ______ in a stolen car before the police arrived.", options: ["get away", "get off", "get over", "get by"], correctAnswer: "A" },
  { id: 81, text: "This gloomy and rainy weather is really ______ me ______. I feel so sad.", options: ["getting / up", "getting / down", "getting / over", "getting / in"], correctAnswer: "B" },
  { id: 82, text: "The committee ______ a new proposal to solve the city's traffic problem.", options: ["put forward", "put down", "put through", "put away"], correctAnswer: "A" },
  { id: 83, text: "\"Could you ______ me ______ to the manager, please?\" - \"Certainly, hold the line.\"", options: ["put / up", "put / through", "put / out", "put / off"], correctAnswer: "B" },
  { id: 84, text: "The weather looked bad this morning, but it ______ to be a beautiful day.", options: ["turned out", "turned into", "turned around", "turned up"], correctAnswer: "A" },
  { id: 85, text: "The price of petrol has ______ significantly over the past few months.", options: ["gone down", "gone up", "gone off", "gone out"], correctAnswer: "B" },
  { id: 86, text: "\"May I use your telephone?\" - \"Yes, please ______.\"", options: ["go ahead", "go over", "go away", "go back"], correctAnswer: "A" },
  { id: 87, text: "Please wipe your dirty shoes on the mat before you ______.", options: ["come from", "come out", "come in", "come off"], correctAnswer: "C" },
  { id: 88, text: "I'm going to England next week, and I won't ______ until next month.", options: ["come across", "come back", "come up with", "come down with"], correctAnswer: "B" },
  { id: 89, text: "I borrowed her dictionary and I must ______ it ______ tomorrow.", options: ["give / up", "give / back", "give / away", "give / in"], correctAnswer: "B" },
  { id: 90, text: "The famous author is going to ______ a new sci-fi book next month.", options: ["bring out", "bring down", "bring up", "bring about"], correctAnswer: "A" },
  { id: 91, text: "After five years of dating, Mary and John sadly decided to ______.", options: ["break out", "break into", "break down", "break up"], correctAnswer: "D" },
  { id: 92, text: "I am in a meeting right now. Can I ______ you ______ in ten minutes?", options: ["call / off", "call / for", "call / back", "call / up"], correctAnswer: "C" },
  { id: 93, text: "This new fashion trend is starting to ______ among teenagers.", options: ["catch up with", "catch on", "catch on", "come off"], correctAnswer: "B" },
  { id: 94, text: "If you make a mistake on the exam paper, just ______ it ______ and write the correct answer above it.", options: ["leave / out", "cross / out", "wipe / out", "point / out"], correctAnswer: "B" },
  { id: 95, text: "His grandfather ______ peacefully in his sleep last night.", options: ["passed away", "passed out", "died out", "went away"], correctAnswer: "A" },
  { id: 96, text: "The tour guide ______ the historical buildings as the bus drove past.", options: ["pointed out", "found out", "left out", "stood out"], correctAnswer: "A" },
  { id: 97, text: "She always wears bright colors because she likes to ______ in a crowd.", options: ["stand by", "stand out", "stand up", "stand for"], correctAnswer: "B" },
  { id: 98, text: "The terrible earthquake ______ the entire village in just a few minutes.", options: ["wiped out", "put out", "cleared up", "set off"], correctAnswer: "A" },
  { id: 99, text: "I don't entirely ______ his views on the environment, but he makes some good points.", options: ["go along with", "keep up with", "get on with", "put up with"], correctAnswer: "A" },
  { id: 100, text: "He ______ and saw that someone was following him.", options: ["turned out", "turned up", "turned around", "turned into"], correctAnswer: "C" },
];
